version: "2"
services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - myapp:/wordpress
    restart: always
    env_file:
      - ../.env
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - mydata:/var/lib/mysql
    restart: always
    env_file:
      - ../.env
  wordpress:
    depends_on:
      - mariadb
    env_file:
      - ../.env
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - myapp:/wordpress
    restart: always
volumes:
  myapp:
  mydata:
networks:
  default:
