version: "2"
services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - myapp:/wordpress
    restart: always
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - myapp:/wordpress
    restart: always
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - myapp:/wordpress
    restart: always
volumes:
  myapp:
networks:
  default:
