version: "2"
services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
      - 82:82
      - 81:81
    volumes:
      - myapp:/home/otmallah/data/wordpress
      - mysite:/page
    restart: always
    env_file:
      - ../.env
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - mydata:/var/lib/mysql
    restart: always
    env_file:
      - ../.env
  ctop :
    tty: true
    build : ./requirements/bonus/ctop
    image: ctop
    restart : always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ftp :
    env_file:
      - ../.env
    build : ./requirements/bonus/ftp
    image: ftp
    restart : always
    ports :
      - 20:20
      - 21:21
    volumes:
      - myapp:/home/otmallah/data/wordpress
  redis:
    image: redis
    build : ./requirements/bonus/redis
    restart : always  
  wordpress:
    depends_on:
      - mariadb
    env_file:
      - ../.env
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - myapp:/home/otmallah/data/wordpress
    restart: always
  site:
    depends_on:
      - nginx
    build: ./requirements/bonus/simple_site
    image : simple_site
    volumes:
      - mysite:/page
    restart : always
  adminer:
    build: ./requirements/bonus/adminer
    restart: always
    image: adminer
    ports:
      - 8080:80
volumes:
  myapp:
    driver: local
    driver_opts:
      type: none
      device: /home/otmallah/data/wordpress
      o: bind
  mydata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/otmallah/data/mysql
  mysite:
networks:
  default:

