version: "2"
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
    networks:
      - default
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    depends_on:
      - wordpress
    ports :
      - 800:800
    networks:
      - default
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    networks :
      - default
    depends_on:
      - nginx
networks:
  default: