version: "2"
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
      - 80:80
    networks:
      - default
    volumes:
      - myapp:/root
    depends_on:
      - wordpress
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    depends_on:
      - wordpress
    networks:
      - default
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - myapp:/root
    networks :
      - default
volumes:
  myapp:
networks:
  default:



  // php-fpm 
  // config.php
  