version: "2"
services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - myapp:/home/otmallah/data/wordpress
      - mysite:/page
    restart: always
    env_file:
      - ../.env
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - mydata:/var/lib/mysql
    restart: always
    env_file:
      - ../.env
  wordpress:
    depends_on:
      - mariadb
    env_file:
      - ../.env
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - myapp:/home/otmallah/data/wordpress
    restart: always
  site:
    depends_on:
      - nginx
    build: ./requirements/bonus/simple_site
    image : simple_site
    volumes:
      - mysite:/page
    restart : always
volumes:
  myapp:
  mydata:
  mysite:
networks:
  default:
